In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\idowe\MyProjects\data-science-course-HIT\diamonds.csv", index_col = 0)

In [ ]:
df.head() # natively showsd 10 rows from the code

   carat      cut color clarity  depth  table  price     x     y     z
1   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
2   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
3   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
4   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
5   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [4]:
df.head(10)

    carat        cut color clarity  depth  table  price     x     y     z
1    0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
2    0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
3    0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
4    0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
5    0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
6    0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
7    0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
8    0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53
9    0.22       Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
10   0.23  Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39

In [5]:
df.tail(10)

       carat        cut color clarity  depth  table  price     x     y     z
53931   0.71    Premium     E     SI1   60.5   55.0   2756  5.79  5.74  3.49
53932   0.71    Premium     F     SI1   59.8   62.0   2756  5.74  5.73  3.43
53933   0.70  Very Good     E     VS2   60.5   59.0   2757  5.71  5.76  3.47
53934   0.70  Very Good     E     VS2   61.2   59.0   2757  5.69  5.72  3.49
53935   0.72    Premium     D     SI1   62.7   59.0   2757  5.69  5.73  3.58
53936   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53937   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53938   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53939   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53940   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64